on: push
name: Verify the module
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node: '10.x'
      - name: install
        run: npm install
      - name: verify_all
        run: npm run verify_all
