on: push
name: Verify the module
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      uses: actions/npm@1.0.0
      with:
        args: ci
    - name: verify_all
      uses: actions/npm@1.0.0
      with:
        args: run verify_all
